### ISSUE TITLE
"Press any key" prompt doesn't accept any key except "Return" key

### ISSUE THREAD

**Issue by chauhanVritul** [ByteBaker/ubuntu21-btfix#1]
Steps to recreate:
1. Have Ubuntu (21.04+) running
2. Open your preferred terminal
3. run the command
4. press any key to continue
5. *process running*
6. after the patch is successful you'll get the before-mentioned prompt
7. doesn't take any key input other than "return" key

**Comment by ByteBaker** [comment]
Thank you for your valuable feedback. The update has now been committed and the issue closed.
